// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelDownload() {
  return window['go']['main']['App']['CancelDownload']();
}

export function ChooseOutputDir(arg1) {
  return window['go']['main']['App']['ChooseOutputDir'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetAvailableQualities(arg1) {
  return window['go']['main']['App']['GetAvailableQualities'](arg1);
}

export function GetSystemLanguage() {
  return window['go']['main']['App']['GetSystemLanguage']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}
