// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelDownload():Promise<void>;

export function ChooseOutputDir(arg1:string):Promise<string>;

export function ClearHistory():Promise<void>;

export function GetAvailableQualities(arg1:string):Promise<Array<string>>;

export function GetSystemLanguage():Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function LoadHistory():Promise<Array<main.HistoryEntry>>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function StartDownload(arg1:main.DownloadRequest):Promise<void>;
